✨ #175 Ability to disable Haptic Feedback
MrKai77/Loop pull request #176
Opened 2024-01-17 18:28 UTC by cyborg-joshi

The changes made in commit "Ability to disable Trackpad Haptic Feedback #175" allow users to control whether Trackpad Haptic Feedback is enabled or disabled through a new setting.

2024-01-18 01:01 UTC, MrKai77 commented
Looks good so far! Would you also be able to add a toggle button in the "More" tab of the settings window to enable/disable this, under a new section called "Accessibility"?

2024-01-18 06:12 UTC, cyborg-joshi commented
Thank you for your feedback, @MrKai77 ! I've implemented the requested changes:
- Added a toggle button in the "More" tab under a new section called "Accessibility" to enable/disable the feature.
- Renamed `enableTrackpadHapticFeedback` to `enableHapticFeedback` for clarity.

<img width="759" alt="image" src="https://github.com/MrKai77/Loop/assets/91533278/08fe23a1-b3db-409d-a8fb-6ede9a79d27c">

2024-01-21 22:26 UTC, MrKai77 commented
@cyborg-joshi any updates on this? I'm planning to make a release soon, and I'd love to have this in it :)

2024-01-22 05:19 UTC, cyborg-joshi commented
@MrKai77 > * Added a toggle button in the "More" tab under a new section called "Accessibility" to enable/disable the feature

and made the commit too

2024-01-22 05:57 UTC, MrKai77 commented
Oh @cyborg-joshi I think you may have forgotten to read the code review? I added some feedback :)

2024-01-23 20:51 UTC, MrKai77 commented
I'll convert this to a draft for now as it is not ready for merge.

2024-01-28 17:57 UTC, MrKai77 commented
@cyborg-joshi any updates? Let me know if you need help getting to the code review :)

2024-01-29 06:54 UTC, cyborg-joshi commented
@MrKai77   thank you for the prompt. I'd appreciate a bit more clarity on the specific changes or updates you're looking for in the code review. Could you please provide a brief summary or point out the areas that need attention? This will help me address your feedback more effectively. Thanks!

2024-01-29 07:33 UTC, mrkai77 commented on Loop/Settings/MoreSettingsView.swift
> +                            Text("Current version: \(Bundle.main.appVersion) (\(Bundle.main.appBuild))")
Please revert this change; not related to this PR

2024-01-29 07:33 UTC, mrkai77 commented on Loop/Settings/MoreSettingsView.swift
> +
Remove blank newlines at end of file

2024-01-29 07:33 UTC, mrkai77 commented on Loop/Settings/MoreSettingsView.swift
> +            }
Looks good!
I'd recommend using `Section("Accessibility")` :)
Also, now that I'm looking at this, I think it would be better if this section was in between the Stage Manager section and the Permissions section.

2024-01-29 07:36 UTC, MrKai77 commented
@cyborg-joshi I'm so sorry! It seems as if I forgot to submit the code review 😅
Now that I have submitted it, you should be able to view it above, and make the needed changes :)

2024-01-29 13:41 UTC, cyborg-joshi commented on Loop/Settings/MoreSettingsView.swift
> +            }
<img width="616" alt="image" src="https://github.com/MrKai77/Loop/assets/91533278/6cc969d1-2f14-40a0-a69e-c683818bda9f">
@MrKai77 
I've made the recommended changes, including using Section("Accessibility") and reordering the sections to place "Accessibility" between "Stage Manager" and "Permissions" for better organization. Please take a look and let me know if there's anything else you'd like to adjust or if you have any additional feedback.

2024-01-29 13:46 UTC, cyborg-joshi commented
@MrKai77  made the necessary changes

2024-01-29 21:24 UTC, MrKai77 commented
@cyborg-joshi  this looks good! But it seems like you committed the changes to your `develop` branch rather than `cyborg_joshi-#175`, so those changes aren't currently visible in this PR. Would you be able to recommit that in the correct branch? Thanks!

2024-01-30 04:58 UTC, cyborg-joshi commented
@MrKai77  Sure, I'll recommit the changes to the correct branch (cyborg_joshi-#175). Thank you for pointing that out!

2024-01-30 05:27 UTC, MrKai77 requested changes

2024-01-30 05:27 UTC, MrKai77 commented on Loop/Managers/LoopManager.swift
> +
Fix indentation

2024-01-30 05:27 UTC, MrKai77 commented on Loop/Settings/MoreSettingsView.swift
> +                            Text("Current version: \(Bundle.main.appVersion) (\(Bundle.main.appBuild))")
Still to be fixed :)

2024-01-30 06:13 UTC, cyborg-joshi commented
@MrKai77 I've made the changes to the MoreSettingsView.swift file. Are these changes okay, or did I misunderstand the modifications? Please let me know if any further adjustments are needed.

2024-01-30 08:27 UTC, MrKai77 requested changes

2024-01-30 08:27 UTC, MrKai77 commented on Loop/Settings/MoreSettingsView.swift
> +                            }
Use 
```swift
// swiftlint:disable:next line_length
Text("Current version: \(Bundle.main.appVersion) (\(Bundle.main.appBuild)) \(Image(systemName: "doc.on.clipboard"))")
```

2024-01-30 08:27 UTC, MrKai77 commented
Yup, the changes you made to `MoreSettingsView.swift` are perfect, except for the part where you changed the clipboard icon in the text that shows the version number. It should be this: 
```swift
Text("Current version: \(Bundle.main.appVersion) (\(Bundle.main.appBuild)) \(Image(systemName: "doc.on.clipboard"))")
```
This way, all the modifiers that are applied to the text are also applied to the icon.

As for the "Fix indentation" comment, you can clearly see that your `if` statement is off by one indent, as well as that there are trailing spaces on the lines, as shown below:
![Screenshot 2024-01-30 at 1 24 46 AM](https://github.com/MrKai77/Loop/assets/68963405/b143af03-2cae-4282-9c31-1438cb1161b7)

2024-01-30 08:55 UTC, cyborg-joshi commented
@MrKai77 Thank you for providing the details. I've made the adjustments to the 'MoreSettingsView.swift' file according to your specifications. 
I also reviewed the 'Fix indentation' comment and addressed the issue by adjusting the indentation and removing trailing spaces. Please have a look and let me know if everything meets your expectations.
if still any minor changes
please do it for me

2024-01-30 17:54 UTC, MrKai77 approved these changes

2024-01-30 17:55 UTC, MrKai77 commented
Looks good!

2024-01-30 17:55 UTC, merged