✨ Import from Rectangle (+ Pro)
MrKai77/Loop pull request #500
Opened 2024-07-09 05:13 UTC by SenpaiHunters

2024-07-09 07:31 UTC, MrKai77 requested changes

2024-07-09 07:31 UTC, MrKai77 commented on Loop/Luminare/Settings/Keybindings/KeybindingsConfiguration.swift
> +        .onReceive(NotificationCenter.default.publisher(for: .keybindsUpdated)) { _ in
Should be able to use `.onRecieve(.keybindsUpdated) {...}`

2024-07-09 07:31 UTC, MrKai77 commented on Loop/Utilities/TranslationLayer.swift
> +//
Would recommend naming this `RectangleTranslationLayer` just in case we decide to implement more importers

2024-07-09 07:31 UTC, MrKai77 commented on Loop/Utilities/TranslationLayer.swift
> +func translateRectangleConfigToWindowActions(rectangleConfig: RectangleConfig) -> [WindowAction] {
Avoid top-level functions, probably makes sense to put all of these inside a `RectangleTranslationLayer` enum

2024-07-09 07:31 UTC, MrKai77 commented on Loop/Luminare/Loop/AdvancedConfiguration.swift
> +            Button("Import from Rectangle") {
"Import keybinds from Rectangle" might be more descriptive for the user

2024-07-11 06:01 UTC, SenpaiHunters commented
In the most recent push, this optimises the whole `WindowAction+Port` file, and while I was at it, I also made it fully update the UI, as that wasn't in the previous code. This PR should be ready to review now, later we can adjust some code &/or find better places for import button(s) etc.

2024-07-11 20:42 UTC, merged